apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: prod

resources:
  - ../../base
  - secrets.yaml
  - csi-s3-secret.yaml

patches:
  - path: patches/replicas.yaml
  - path: patches/resources.yaml
  - path: patches/affinity.yaml

images:
  - name: mablinov2704/frontend
    newTag: "1.0.0"
  - name: mablinov2704/bff
    newTag: "1.0.0"
  - name: mablinov2704/user-service
    newTag: "1.0.0"
  - name: mablinov2704/message-service
    newTag: "1.0.0"
