# prod credentials — заменить перед деплоем на реальные значения
apiVersion: v1
kind: Secret
metadata:
  name: messager-db-secret
  namespace: messenger
type: Opaque
stringData:
  POSTGRES_USER: "messenger"
  POSTGRES_PASSWORD: "messenger_pass"
  USER_DB_DSN: "host=postgres user=messenger password=messenger_pass dbname=users sslmode=disable"
  MSG_DB_DSN: "host=postgres user=messenger password=messenger_pass dbname=messages sslmode=disable"
  GOOSE_USER_DBSTRING: "host=postgres user=messenger password=messenger_pass dbname=users sslmode=disable"
  GOOSE_MSG_DBSTRING: "host=postgres user=messenger password=messenger_pass dbname=messages sslmode=disable"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: messenger
type: Opaque
stringData:
  accessKeyID: "admin"
  secretAccessKey: "password"
