# prod: frontend, bff, user-service, message-service — минимум 2 реплики
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: messenger
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: messenger
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: messenger
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: messenger
spec:
  replicas: 2
