apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messager-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KiritoZik/k8s-messenger-gitops.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: messenger
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messager-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KiritoZik/k8s-messenger-gitops.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: messenger-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
